version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10
  working_directory: ~/decentralized-electronic-health-record/client
    steps:
      - checkout # special step to check out source code to working directory

      - restore_cache: # special step to restore the dependency cache
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}
            
      - run:
          name: Install dependencies with YARN
          command: yarn install

      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          command: yarn test 

      - store_artifacts: 
          path: test-results

      - store_test_results:
          path: test-results

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
