version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
              - name: Testing abd Building
              - command: "cd client" yarn install yarn test yarn build
workflows:
    build-and-test:
      jobs:
        - build-and-test
